### ISSUE TITLE
[Feature Request] Add Kind: TCOPolicy

### ISSUE THREAD

**Issue by segevmatuti1** [coralogix/cx-operator#111]
Motivation - 
I want to provide developers autonomy for creating TCO policies in the system, with access control (only for their service)
each policy will be part of their helm chart (gaining both **access control** and **IAC**)

Proposal - 
```
Kind: TCOPolicy
metadata:
    name: remove-debug
spec:
    applications: [ list ] 
    subsystem: [ list ] 
    severity: [ list ]
    priority: [ list ]
```
